global:
  scrape_interval: 15s      # 每15秒采集一次数据
  evaluation_interval: 15s  # 每15秒评估一次告警规则
  scrape_timeout: 10s       # 默认采集超时时间

# Alertmanager 配置（如需启用，取消注释）
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "localhost:9093"  # Alertmanager 默认端口

# 告警规则文件路径
rule_files:
  - "alert.rules.yml"        # 自定义告警规则文件

# 监控目标配置
scrape_configs:
  # 监控 Prometheus 自身
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 监控 Node Exporter（添加你的服务器IP）
  - job_name: "node"
    static_configs:
      - targets: ["13.231.136.144:9100"]  # 替换为你的 Node Exporter IP
        labels:
          instance: "your-server-name"  # 自定义实例名称（如主机名）
    # 可选：重命名标签，确保 instance 字段规范
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):\d+'
        replacement: '$1'  # 去掉端口号，仅保留IP

  # 可选：其他监控任务（如 MySQL、Redis）
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-server:9104"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-server:10163"]
#